# Generated by Django 3.0.1 on 2019-12-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyChange',
        ),
    ]
