# Generated by Django 3.0.1 on 2019-12-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_moneychange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyChange',
        ),
    ]
